import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "@/Component/Navber";
import BooksProvider from "@/Context/BooksContexts";
import { ToastContainer } from "react-toastify";
import Footer from "@/Component/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <BooksProvider>
          <Navber></Navber>
          {children}
          <Footer></Footer>
          <ToastContainer />
        </BooksProvider>
      </body>
    </html>
  );
}
